In [16]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Create a sample dataset
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler on the data and transform the data
scaled_data = scaler.fit_transform(data)

# Print the original data
print("Original data:")
print(data)

# Print the scaled data
print("\nScaled data:")
print(scaled_data)

Original data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Scaled data:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [17]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Create a sample dataset in a pandas DataFrame
data = {
    'A': [10, 20, 30, 40, 50],
    'B': [1, 2, 3, 4, 5],
    'C': [5, 10, 15, 20, 25]
}
df = pd.DataFrame(data)

# Select the numerical columns to scale
numerical_cols = ['A', 'B', 'C']
X = df[numerical_cols]

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler on the data and transform the numerical columns
X_scaled = scaler.fit_transform(X)

# Replace the original numerical columns with the scaled values
df[numerical_cols] = X_scaled

# Print the original and scaled data
print("Original data:")
print(df)


Original data:
      A     B     C
0  0.00  0.00  0.00
1  0.25  0.25  0.25
2  0.50  0.50  0.50
3  0.75  0.75  0.75
4  1.00  1.00  1.00


In [18]:
import pandas as pd
from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler

# Load the Diabetes dataset from scikit-learn
diabetes = datasets.load_diabetes()

# Create a pandas DataFrame from the dataset
df = pd.DataFrame(data=diabetes.data, columns=diabetes.feature_names)

# Select the numerical columns to scale
numerical_cols = df.columns
X = df[numerical_cols]

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler on the data and transform the numerical columns
X_scaled = scaler.fit_transform(X)

# Replace the original numerical columns with the scaled values
df[numerical_cols] = X_scaled

# Print the original and scaled data
print("Original data:")
print(df.head())

Original data:
        age  sex       bmi        bp        s1        s2        s3        s4  \
0  0.666667  1.0  0.582645  0.549296  0.294118  0.256972  0.207792  0.282087   
1  0.483333  0.0  0.148760  0.352113  0.421569  0.306773  0.623377  0.141044   
2  0.883333  1.0  0.516529  0.436620  0.289216  0.258964  0.246753  0.282087   
3  0.083333  0.0  0.301653  0.309859  0.495098  0.447211  0.233766  0.423131   
4  0.516667  0.0  0.206612  0.549296  0.465686  0.417331  0.389610  0.282087   

         s5        s6  
0  0.562217  0.439394  
1  0.222437  0.166667  
2  0.496578  0.409091  
3  0.572923  0.469697  
4  0.362385  0.333333  


In [21]:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [22]:
df

age  sex       bmi        bp        s1        s2        s3  \
0    0.666667  1.0  0.582645  0.549296  0.294118  0.256972  0.207792   
1    0.483333  0.0  0.148760  0.352113  0.421569  0.306773  0.623377   
2    0.883333  1.0  0.516529  0.436620  0.289216  0.258964  0.246753   
3    0.083333  0.0  0.301653  0.309859  0.495098  0.447211  0.233766   
4    0.516667  0.0  0.206612  0.549296  0.465686  0.417331  0.389610   
..        ...  ...       ...       ...       ...       ...       ...   
437  0.683333  1.0  0.421488  0.704225  0.431373  0.359562  0.259740   
438  0.466667  1.0  0.285124  0.183099  0.627451  0.619522  0.259740   
439  0.683333  1.0  0.285124  0.530563  0.318627  0.323705  0.272727   
440  0.283333  0.0  0.495868  0.464789  0.509804  0.416335  0.259740   
441  0.283333  0.0  0.066116  0.126761  0.750000  0.456175  0.974026   

           s4        s5        s6  
0    0.282087  0.562217  0.439394  
1    0.141044  0.222437  0.166667  
2    0.282087  0.496578  0.409091  
3    0.423131  0.572923  0.469697  
4    0.282087  0.362385  0.333333  
..        ...       ...       ...  
437  0.282087  0.605672  0.530303  
438  0.423131  0.415810  0.666667  
439  0.249647  0.305030  0.560606  
440  0.393512  0.657026  0.409091  
441  0.141044  0.469304  0.515152  

[442 rows x 10 columns]

In [20]:
X_scaled 

array([[0.66666667, 1.        , 0.58264463, ..., 0.28208745, 0.562217  ,
        0.43939394],
       [0.48333333, 0.        , 0.14876033, ..., 0.14104372, 0.22243673,
        0.16666667],
       [0.88333333, 1.        , 0.51652893, ..., 0.28208745, 0.49657763,
        0.40909091],
       ...,
       [0.68333333, 1.        , 0.28512397, ..., 0.24964739, 0.30503001,
        0.56060606],
       [0.28333333, 0.        , 0.49586777, ..., 0.39351199, 0.65702552,
        0.40909091],
       [0.28333333, 0.        , 0.0661157 , ..., 0.14104372, 0.46930394,
        0.51515152]])